// Pre-loaded Kroger store graph for demo/offline mode.
// Converted from data/store_graph.json — nodes keep id/name/x/y, links renamed to edges with from/to.

export const MOCK_STORE_NAME = "Kroger – Demo Store";

export const mockMapData = {
  nodes: [
    { id: "0",             name: "Aisle 0 - Front Perimeter",       x: 1.5, y: 0.5  },
    { id: "1",             name: "Aisle 1 - Dairy & Bakery",        x: 1.5, y: 2.5  },
    { id: "2",             name: "Aisle 2 - Dry Goods",             x: 2.5, y: 2.5  },
    { id: "3",             name: "Aisle 3 - Baking & Coffee",       x: 3.5, y: 2.5  },
    { id: "4",             name: "Aisle 4 - Breakfast & Crackers",  x: 4.5, y: 2.5  },
    { id: "5",             name: "Aisle 5 - Snacks",                x: 5.5, y: 2.5  },
    { id: "6",             name: "Aisle 6 - Beverages",             x: 6.5, y: 2.5  },
    { id: "7",             name: "Aisle 7 - Personal Care",         x: 7.5, y: 1.5  },
    { id: "8",             name: "Aisle 8 - Frozen Foods",          x: 1.5, y: 1.5  },
    { id: "9",             name: "Aisle 9 - Snacks & Popcorn",      x: 8.5, y: 2.5  },
    { id: "11",            name: "Aisle 11 - Canned Goods",         x: 4.5, y: 1.5  },
    { id: "12",            name: "Aisle 12 - Oils & Condiments",    x: 7.5, y: 2.5  },
    { id: "16",            name: "Aisle 16 - International & Bread",x: 6.5, y: 1.5  },
    { id: "18",            name: "Aisle 18 - Canned Sauces",        x: 5.5, y: 1.5  },
    { id: "22",            name: "Aisle 22 - Granola & Syrup",      x: 8.0, y: 2.5  },
    { id: "34",            name: "Aisle 34 - Yogurt",               x: 4.5, y: 4.0  },
    { id: "40",            name: "Aisle 40 - Frozen Meals",         x: 2.5, y: 1.5  },
    { id: "42",            name: "Aisle 42 - Frozen Desserts",      x: 3.5, y: 1.5  },
    { id: "100",           name: "Dairy (Refrigerated)",            x: 1.5, y: 4.0  },
    { id: "101",           name: "Meat & Poultry",                  x: 7.5, y: 4.0  },
    { id: "105",           name: "Produce - Greens",                x: 6.5, y: 0.5  },
    { id: "152",           name: "Bakery",                          x: 0.5, y: 3.0  },
    { id: "351",           name: "Produce - Fruit",                 x: 7.5, y: 0.5  },
    { id: "352",           name: "Produce - Vegetables",            x: 8.5, y: 0.5  },
    { id: "447",           name: "Deli Fresh",                      x: 9.5, y: 1.5  },
    { id: "cleaning",      name: "Cleaning & Household",            x: 0.5, y: 1.5  },
    { id: "vitamins",      name: "Vitamins & Supplements",          x: 0.5, y: 2.5  },
    { id: "pharmacy",      name: "Pharmacy",                        x: 0.5, y: 3.5  },
    { id: "entrance_left", name: "Entrance (Left)",                 x: 0.5, y: -0.8 },
    { id: "entrance_right",name: "Entrance (Right)",                x: 9.5, y: -0.8 },
    { id: "checkout_1",    name: "Checkout Lane 1",                 x: 11.0, y: 2.0 },
    { id: "checkout_2",    name: "Checkout Lane 2",                 x: 11.0, y: 3.0 },
    { id: "checkout_3",    name: "Checkout Lane 3 (Express)",       x: 11.0, y: 4.0 },
    { id: "exit",          name: "Exit",                            x: 11.0, y: 5.0 },
  ],
  edges: [
    { from: "0",             to: "152"          },
    { from: "0",             to: "1"            },
    { from: "0",             to: "8"            },
    { from: "0",             to: "105"          },
    { from: "0",             to: "cleaning"     },
    { from: "0",             to: "entrance_left"},
    { from: "1",             to: "100"          },
    { from: "1",             to: "152"          },
    { from: "1",             to: "2"            },
    { from: "1",             to: "8"            },
    { from: "1",             to: "0"            },
    { from: "2",             to: "1"            },
    { from: "2",             to: "3"            },
    { from: "2",             to: "40"           },
    { from: "3",             to: "2"            },
    { from: "3",             to: "4"            },
    { from: "3",             to: "42"           },
    { from: "4",             to: "34"           },
    { from: "4",             to: "3"            },
    { from: "4",             to: "5"            },
    { from: "4",             to: "11"           },
    { from: "5",             to: "4"            },
    { from: "5",             to: "6"            },
    { from: "5",             to: "18"           },
    { from: "6",             to: "5"            },
    { from: "6",             to: "12"           },
    { from: "6",             to: "16"           },
    { from: "7",             to: "16"           },
    { from: "7",             to: "447"          },
    { from: "7",             to: "12"           },
    { from: "7",             to: "105"          },
    { from: "8",             to: "40"           },
    { from: "8",             to: "1"            },
    { from: "8",             to: "0"            },
    { from: "8",             to: "cleaning"     },
    { from: "9",             to: "101"          },
    { from: "9",             to: "22"           },
    { from: "9",             to: "447"          },
    { from: "9",             to: "checkout_1"   },
    { from: "11",            to: "42"           },
    { from: "11",            to: "18"           },
    { from: "11",            to: "4"            },
    { from: "12",            to: "6"            },
    { from: "12",            to: "22"           },
    { from: "12",            to: "7"            },
    { from: "16",            to: "18"           },
    { from: "16",            to: "7"            },
    { from: "16",            to: "6"            },
    { from: "18",            to: "11"           },
    { from: "18",            to: "16"           },
    { from: "18",            to: "5"            },
    { from: "22",            to: "101"          },
    { from: "22",            to: "12"           },
    { from: "22",            to: "9"            },
    { from: "447",           to: "7"            },
    { from: "447",           to: "9"            },
    { from: "447",           to: "352"          },
    { from: "447",           to: "checkout_1"   },
    { from: "cleaning",      to: "vitamins"     },
    { from: "cleaning",      to: "8"            },
    { from: "cleaning",      to: "0"            },
    { from: "cleaning",      to: "entrance_left"},
    { from: "vitamins",      to: "cleaning"     },
    { from: "vitamins",      to: "pharmacy"     },
    { from: "pharmacy",      to: "vitamins"     },
    { from: "pharmacy",      to: "152"          },
    { from: "34",            to: "100"          },
    { from: "34",            to: "101"          },
    { from: "34",            to: "4"            },
    { from: "40",            to: "8"            },
    { from: "40",            to: "42"           },
    { from: "40",            to: "2"            },
    { from: "42",            to: "40"           },
    { from: "42",            to: "11"           },
    { from: "42",            to: "3"            },
    { from: "100",           to: "34"           },
    { from: "100",           to: "1"            },
    { from: "100",           to: "152"          },
    { from: "101",           to: "34"           },
    { from: "101",           to: "9"            },
    { from: "101",           to: "22"           },
    { from: "101",           to: "checkout_1"   },
    { from: "152",           to: "100"          },
    { from: "152",           to: "1"            },
    { from: "152",           to: "0"            },
    { from: "152",           to: "pharmacy"     },
    { from: "152",           to: "entrance_left"},
    { from: "105",           to: "351"          },
    { from: "105",           to: "7"            },
    { from: "105",           to: "0"            },
    { from: "105",           to: "entrance_right"},
    { from: "351",           to: "105"          },
    { from: "351",           to: "352"          },
    { from: "352",           to: "351"          },
    { from: "352",           to: "447"          },
    { from: "352",           to: "entrance_right"},
    { from: "entrance_left", to: "0"            },
    { from: "entrance_left", to: "cleaning"     },
    { from: "entrance_left", to: "152"          },
    { from: "entrance_right",to: "352"          },
    { from: "entrance_right",to: "105"          },
    { from: "checkout_1",    to: "9"            },
    { from: "checkout_1",    to: "447"          },
    { from: "checkout_1",    to: "101"          },
    { from: "checkout_1",    to: "checkout_2"   },
    { from: "checkout_2",    to: "checkout_1"   },
    { from: "checkout_2",    to: "checkout_3"   },
    { from: "checkout_3",    to: "checkout_2"   },
    { from: "checkout_3",    to: "exit"         },
    { from: "exit",          to: "checkout_3"   },
  ],
};
