// Pre-loaded Kroger store graph for demo/offline mode.
// Converted from data/store_graph.json — nodes keep id/name/x/y, links renamed to edges with from/to.

export const MOCK_STORE_NAME = "Kroger – Demo Store";

// Product catalog per aisle — mirrors tools/kroger.py NODE_MAP
export const MOCK_AISLE_INFO = {
  "0":   { name: "Aisle 0 - Front Perimeter",      audio: "Front Perimeter — impulse buys, candy, and mixed goods near the entrance.", items: [{ product: "ground beef", side: "left side", shelf: "bottom shelf" }, { product: "ham", side: "left side", shelf: "lower shelf" }, { product: "cake", side: "left side", shelf: "top shelf" }, { product: "cookies", side: "left side", shelf: "middle shelf" }, { product: "bananas", side: "center", shelf: "display bin" }, { product: "salmon", side: "left side", shelf: "bottom shelf" }] },
  "1":   { name: "Aisle 1 - Dairy & Bakery",        audio: "Aisle 1 — Dairy and Bakery. Butter and cheese on the left, bread and tea on the right.", items: [{ product: "butter", side: "left side", shelf: "middle shelf" }, { product: "cheese", side: "left side", shelf: "middle shelf" }, { product: "parmesan", side: "left side", shelf: "upper shelf" }, { product: "mozzarella", side: "left side", shelf: "upper shelf" }, { product: "cheddar", side: "left side", shelf: "middle shelf" }, { product: "sour cream", side: "right side", shelf: "middle shelf" }, { product: "bread", side: "right side", shelf: "middle shelf" }, { product: "tea", side: "left side", shelf: "upper shelf" }, { product: "cream cheese", side: "left side", shelf: "upper shelf" }, { product: "bacon", side: "right side", shelf: "lower shelf" }] },
  "2":   { name: "Aisle 2 - Dry Goods",             audio: "Aisle 2 — Dry Goods. Pasta and rice on the left, quinoa and couscous on the right.", items: [{ product: "pasta", side: "left side", shelf: "middle shelf" }, { product: "spaghetti", side: "left side", shelf: "middle shelf" }, { product: "penne", side: "left side", shelf: "middle shelf" }, { product: "noodles", side: "left side", shelf: "lower shelf" }, { product: "rice", side: "right side", shelf: "middle shelf" }, { product: "quinoa", side: "right side", shelf: "upper shelf" }, { product: "couscous", side: "right side", shelf: "lower shelf" }, { product: "ketchup", side: "right side", shelf: "upper shelf" }, { product: "mayonnaise", side: "right side", shelf: "middle shelf" }, { product: "hot sauce", side: "right side", shelf: "lower shelf" }] },
  "3":   { name: "Aisle 3 - Baking & Coffee",       audio: "Aisle 3 — Baking and Coffee. Flour and sugar left, coffee and soup right.", items: [{ product: "flour", side: "left side", shelf: "lower shelf" }, { product: "sugar", side: "left side", shelf: "middle shelf" }, { product: "salt", side: "left side", shelf: "middle shelf" }, { product: "pepper", side: "left side", shelf: "upper shelf" }, { product: "coffee", side: "right side", shelf: "upper shelf" }, { product: "soup", side: "right side", shelf: "middle shelf" }, { product: "orange juice", side: "left side", shelf: "upper shelf" }, { product: "vinegar", side: "left side", shelf: "lower shelf" }, { product: "chocolate chips", side: "left side", shelf: "upper shelf" }, { product: "brownie mix", side: "left side", shelf: "top shelf" }] },
  "4":   { name: "Aisle 4 - Breakfast & Crackers",  audio: "Aisle 4 — Breakfast and Crackers. Oatmeal and cereal left, pretzels and crackers right.", items: [{ product: "oatmeal", side: "left side", shelf: "middle shelf" }, { product: "cereal", side: "right side", shelf: "middle shelf" }, { product: "pancake mix", side: "right side", shelf: "upper shelf" }, { product: "pretzels", side: "right side", shelf: "lower shelf" }, { product: "crackers", side: "right side", shelf: "bottom shelf" }, { product: "peanut butter", side: "right side", shelf: "upper shelf" }, { product: "jelly", side: "right side", shelf: "middle shelf" }, { product: "jam", side: "right side", shelf: "lower shelf" }] },
  "5":   { name: "Aisle 5 - Snacks",                audio: "Aisle 5 — Snacks. Chips on the left, sports drinks and rice cakes on the right.", items: [{ product: "chips", side: "left side", shelf: "middle shelf" }, { product: "sports drink", side: "left side", shelf: "lower shelf" }, { product: "waffles", side: "right side", shelf: "middle shelf" }, { product: "rice cakes", side: "right side", shelf: "lower shelf" }, { product: "shrimp", side: "left side", shelf: "bottom shelf" }] },
  "6":   { name: "Aisle 6 - Beverages",             audio: "Aisle 6 — Beverages. Water left, soda and sparkling water right.", items: [{ product: "water", side: "left side", shelf: "lower shelf" }, { product: "soda", side: "right side", shelf: "middle shelf" }, { product: "sparkling water", side: "left side", shelf: "middle shelf" }, { product: "cola", side: "right side", shelf: "lower shelf" }] },
  "7":   { name: "Aisle 7 - Personal Care",         audio: "Aisle 7 — Personal Care. Toothpaste, soap, and deodorant on both sides.", items: [{ product: "toothpaste", side: "left side", shelf: "upper shelf" }, { product: "soap", side: "left side", shelf: "middle shelf" }, { product: "deodorant", side: "left side", shelf: "lower shelf" }, { product: "lotion", side: "right side", shelf: "middle shelf" }, { product: "shampoo", side: "right side", shelf: "upper shelf" }] },
  "8":   { name: "Aisle 8 - Frozen Foods",          audio: "Aisle 8 — Frozen Foods. Frozen pizza and vegetables left, ice cream right.", items: [{ product: "frozen pizza", side: "left side", shelf: "middle shelf" }, { product: "frozen vegetables", side: "left side", shelf: "lower shelf" }, { product: "ice cream", side: "left side", shelf: "bottom shelf" }, { product: "popsicles", side: "left side", shelf: "lower shelf" }, { product: "frozen waffles", side: "right side", shelf: "upper shelf" }, { product: "frozen burritos", side: "right side", shelf: "lower shelf" }] },
  "9":   { name: "Aisle 9 - Snacks & Popcorn",      audio: "Aisle 9 — Snacks and Popcorn. Popcorn and nuts on the right.", items: [{ product: "popcorn", side: "right side", shelf: "middle shelf" }, { product: "nuts", side: "right side", shelf: "upper shelf" }, { product: "trail mix", side: "right side", shelf: "lower shelf" }] },
  "11":  { name: "Aisle 11 - Canned Goods",         audio: "Aisle 11 — Canned Goods. Broth, canned corn, and tuna on both sides.", items: [{ product: "broth", side: "left side", shelf: "upper shelf" }, { product: "canned corn", side: "right side", shelf: "middle shelf" }, { product: "canned tuna", side: "left side", shelf: "middle shelf" }, { product: "canned chicken", side: "right side", shelf: "lower shelf" }] },
  "12":  { name: "Aisle 12 - Oils & Condiments",    audio: "Aisle 12 — Oils and Condiments. Olive oil and cooking oils on the left, condiments right.", items: [{ product: "olive oil", side: "left side", shelf: "middle shelf" }, { product: "vegetable oil", side: "left side", shelf: "lower shelf" }, { product: "cooking spray", side: "right side", shelf: "upper shelf" }, { product: "coconut oil", side: "right side", shelf: "middle shelf" }, { product: "balsamic", side: "left side", shelf: "upper shelf" }] },
  "16":  { name: "Aisle 16 - International & Bread",audio: "Aisle 16 — International and Bread. Tortillas and taco shells left, soy sauce and Asian sauces right.", items: [{ product: "tortillas", side: "left side", shelf: "middle shelf" }, { product: "soy sauce", side: "right side", shelf: "upper shelf" }, { product: "teriyaki sauce", side: "right side", shelf: "middle shelf" }, { product: "taco shells", side: "left side", shelf: "lower shelf" }, { product: "pita bread", side: "left side", shelf: "upper shelf" }] },
  "18":  { name: "Aisle 18 - Canned Sauces",        audio: "Aisle 18 — Canned Sauces. Beans and tomato sauce on the left, pasta sauce and mustard right.", items: [{ product: "canned beans", side: "left side", shelf: "middle shelf" }, { product: "tomato sauce", side: "left side", shelf: "lower shelf" }, { product: "pasta sauce", side: "right side", shelf: "middle shelf" }, { product: "mustard", side: "right side", shelf: "upper shelf" }] },
  "22":  { name: "Aisle 22 - Granola & Syrup",      audio: "Aisle 22 — Granola and Syrup. Granola and maple syrup on the left, honey right.", items: [{ product: "granola", side: "left side", shelf: "middle shelf" }, { product: "maple syrup", side: "left side", shelf: "upper shelf" }, { product: "honey", side: "right side", shelf: "upper shelf" }, { product: "granola bars", side: "right side", shelf: "middle shelf" }] },
  "34":  { name: "Aisle 34 - Yogurt",               audio: "Aisle 34 — Yogurt. Refrigerated section, yogurt and kefir on both sides.", items: [{ product: "yogurt", side: "left side", shelf: "middle shelf" }, { product: "greek yogurt", side: "right side", shelf: "middle shelf" }, { product: "kefir", side: "left side", shelf: "lower shelf" }] },
  "40":  { name: "Aisle 40 - Frozen Meals",         audio: "Aisle 40 — Frozen Meals. Pot pies and frozen dinners in glass freezer cases.", items: [{ product: "pot pie", side: "right side", shelf: "middle shelf" }, { product: "frozen dinners", side: "left side", shelf: "middle shelf" }, { product: "frozen pasta", side: "right side", shelf: "lower shelf" }, { product: "frozen soup", side: "left side", shelf: "lower shelf" }] },
  "42":  { name: "Aisle 42 - Frozen Desserts",      audio: "Aisle 42 — Frozen Desserts. Frozen yogurt and gelato in deep freezer cases.", items: [{ product: "frozen yogurt", side: "right side", shelf: "middle shelf" }, { product: "gelato", side: "left side", shelf: "middle shelf" }, { product: "sorbet", side: "right side", shelf: "lower shelf" }] },
  "100": { name: "Dairy (Refrigerated)",             audio: "Dairy — refrigerated back wall. Milk and eggs on the right.", items: [{ product: "milk", side: "back wall", shelf: "middle shelf" }, { product: "eggs", side: "back wall", shelf: "lower shelf" }, { product: "almond milk", side: "back wall", shelf: "upper shelf" }, { product: "oat milk", side: "back wall", shelf: "middle shelf" }, { product: "heavy cream", side: "back wall", shelf: "upper shelf" }] },
  "101": { name: "Meat & Poultry",                  audio: "Meat and Poultry — refrigerated back wall. Chicken, pork, sausage.", items: [{ product: "chicken breast", side: "back wall", shelf: "bottom shelf" }, { product: "pork", side: "back wall", shelf: "lower shelf" }, { product: "sausage", side: "back wall", shelf: "middle shelf" }, { product: "hot dogs", side: "back wall", shelf: "upper shelf" }, { product: "turkey", side: "back wall", shelf: "lower shelf" }, { product: "steak", side: "back wall", shelf: "middle shelf" }] },
  "105": { name: "Produce - Greens",                audio: "Produce Greens — mist sprayers, fresh smell. Lettuce, spinach, and broccoli on the right.", items: [{ product: "lettuce", side: "right side", shelf: "display bin" }, { product: "spinach", side: "right side", shelf: "lower shelf" }, { product: "broccoli", side: "right side", shelf: "display bin" }, { product: "carrots", side: "left side", shelf: "display bin" }] },
  "152": { name: "Bakery",                          audio: "Bakery — warm bread smell, sourdough and bagels left, croissants and donuts right.", items: [{ product: "sourdough", side: "left side", shelf: "middle shelf" }, { product: "bagels", side: "left side", shelf: "lower shelf" }, { product: "muffins", side: "left side", shelf: "upper shelf" }, { product: "croissants", side: "right side", shelf: "middle shelf" }, { product: "donuts", side: "right side", shelf: "upper shelf" }] },
  "351": { name: "Produce - Fruit",                 audio: "Produce Fruit — open display bins. Apples, grapes, and strawberries ahead.", items: [{ product: "apples", side: "center", shelf: "display bin" }, { product: "grapes", side: "left side", shelf: "display bin" }, { product: "strawberries", side: "left side", shelf: "display bin" }, { product: "oranges", side: "right side", shelf: "display bin" }, { product: "blueberries", side: "center", shelf: "display bin" }] },
  "352": { name: "Produce - Vegetables",            audio: "Produce Vegetables — display bins. Tomatoes, onions, and potatoes on both sides.", items: [{ product: "tomatoes", side: "left side", shelf: "display bin" }, { product: "onions", side: "center", shelf: "display bin" }, { product: "potatoes", side: "right side", shelf: "display bin" }, { product: "peppers", side: "left side", shelf: "display bin" }, { product: "garlic", side: "right side", shelf: "display bin" }] },
  "447": { name: "Deli Fresh",                      audio: "Deli Fresh — refrigerated case, fresh salsa and hummus on the right, deli meats on the left.", items: [{ product: "salsa", side: "right side", shelf: "middle shelf" }, { product: "hummus", side: "right side", shelf: "upper shelf" }, { product: "deli meat", side: "left side", shelf: "middle shelf" }, { product: "guacamole", side: "right side", shelf: "lower shelf" }, { product: "rotisserie chicken", side: "left side", shelf: "display case" }, { product: "potato salad", side: "right side", shelf: "lower shelf" }] },
  "cleaning":      { name: "Cleaning & Household",  audio: "Cleaning and Household — left wall. Dish soap and detergent on the left, paper towels and trash bags on the right.", items: [{ product: "dish soap", side: "left side", shelf: "middle shelf" }, { product: "laundry detergent", side: "left side", shelf: "lower shelf" }, { product: "paper towels", side: "right side", shelf: "upper shelf" }, { product: "trash bags", side: "right side", shelf: "lower shelf" }, { product: "bleach", side: "right side", shelf: "middle shelf" }] },
  "vitamins":      { name: "Vitamins & Supplements", audio: "Vitamins and Supplements — left wall.", items: [{ product: "vitamins", side: "left side", shelf: "upper shelf" }, { product: "protein powder", side: "right side", shelf: "upper shelf" }, { product: "fish oil", side: "left side", shelf: "middle shelf" }, { product: "multivitamin", side: "right side", shelf: "middle shelf" }, { product: "melatonin", side: "right side", shelf: "lower shelf" }] },
  "pharmacy":      { name: "Pharmacy",               audio: "Pharmacy — left wall near bakery. Cold medicine and allergy relief on the left, pain relief and bandages on the right.", items: [{ product: "cold medicine", side: "left side", shelf: "middle shelf" }, { product: "pain relief", side: "right side", shelf: "middle shelf" }, { product: "bandages", side: "left side", shelf: "lower shelf" }, { product: "cough syrup", side: "right side", shelf: "lower shelf" }, { product: "allergy medicine", side: "left side", shelf: "upper shelf" }, { product: "ibuprofen", side: "right side", shelf: "upper shelf" }] },
  "entrance_left": { name: "Entrance (Left)",        audio: "Main entrance, left side. Shopping carts on your right.", items: [] },
  "entrance_right":{ name: "Entrance (Right)",       audio: "Side entrance, right side. Produce section directly ahead.", items: [] },
  "checkout_1":    { name: "Checkout Lane 1",         audio: "Checkout lane 1 — conveyor belt, cashier ahead.", items: [] },
  "checkout_2":    { name: "Checkout Lane 2",         audio: "Checkout lane 2 — self-checkout available.", items: [] },
  "checkout_3":    { name: "Checkout Lane 3 (Express)", audio: "Express lane, 15 items or fewer.", items: [] },
  "exit":          { name: "Exit",                    audio: "Exit — sliding doors ahead. Thank you for shopping.", items: [] },
};

export const mockMapData = {
  nodes: [
    { id: "0",             name: "Aisle 0 - Front Perimeter",       x: 1.5, y: 0.5  },
    { id: "1",             name: "Aisle 1 - Dairy & Bakery",        x: 1.5, y: 2.5  },
    { id: "2",             name: "Aisle 2 - Dry Goods",             x: 2.5, y: 2.5  },
    { id: "3",             name: "Aisle 3 - Baking & Coffee",       x: 3.5, y: 2.5  },
    { id: "4",             name: "Aisle 4 - Breakfast & Crackers",  x: 4.5, y: 2.5  },
    { id: "5",             name: "Aisle 5 - Snacks",                x: 5.5, y: 2.5  },
    { id: "6",             name: "Aisle 6 - Beverages",             x: 6.5, y: 2.5  },
    { id: "7",             name: "Aisle 7 - Personal Care",         x: 7.5, y: 1.5  },
    { id: "8",             name: "Aisle 8 - Frozen Foods",          x: 1.5, y: 1.5  },
    { id: "9",             name: "Aisle 9 - Snacks & Popcorn",      x: 8.5, y: 2.5  },
    { id: "11",            name: "Aisle 11 - Canned Goods",         x: 4.5, y: 1.5  },
    { id: "12",            name: "Aisle 12 - Oils & Condiments",    x: 7.5, y: 2.5  },
    { id: "16",            name: "Aisle 16 - International & Bread",x: 6.5, y: 1.5  },
    { id: "18",            name: "Aisle 18 - Canned Sauces",        x: 5.5, y: 1.5  },
    { id: "22",            name: "Aisle 22 - Granola & Syrup",      x: 8.0, y: 2.5  },
    { id: "34",            name: "Aisle 34 - Yogurt",               x: 4.5, y: 4.0  },
    { id: "40",            name: "Aisle 40 - Frozen Meals",         x: 2.5, y: 1.5  },
    { id: "42",            name: "Aisle 42 - Frozen Desserts",      x: 3.5, y: 1.5  },
    { id: "100",           name: "Dairy (Refrigerated)",            x: 1.5, y: 4.0  },
    { id: "101",           name: "Meat & Poultry",                  x: 7.5, y: 4.0  },
    { id: "105",           name: "Produce - Greens",                x: 6.5, y: 0.5  },
    { id: "152",           name: "Bakery",                          x: 0.5, y: 3.0  },
    { id: "351",           name: "Produce - Fruit",                 x: 7.5, y: 0.5  },
    { id: "352",           name: "Produce - Vegetables",            x: 8.5, y: 0.5  },
    { id: "447",           name: "Deli Fresh",                      x: 9.5, y: 1.5  },
    { id: "cleaning",      name: "Cleaning & Household",            x: 0.5, y: 1.5  },
    { id: "vitamins",      name: "Vitamins & Supplements",          x: 0.5, y: 2.5  },
    { id: "pharmacy",      name: "Pharmacy",                        x: 0.5, y: 3.5  },
    { id: "entrance_left", name: "Entrance (Left)",                 x: 0.5, y: -0.8 },
    { id: "entrance_right",name: "Entrance (Right)",                x: 9.5, y: -0.8 },
    { id: "checkout_1",    name: "Checkout Lane 1",                 x: 11.0, y: 2.0 },
    { id: "checkout_2",    name: "Checkout Lane 2",                 x: 11.0, y: 3.0 },
    { id: "checkout_3",    name: "Checkout Lane 3 (Express)",       x: 11.0, y: 4.0 },
    { id: "exit",          name: "Exit",                            x: 11.0, y: 5.0 },
  ],
  edges: [
    { from: "0",             to: "152"          },
    { from: "0",             to: "1"            },
    { from: "0",             to: "8"            },
    { from: "0",             to: "105"          },
    { from: "0",             to: "cleaning"     },
    { from: "0",             to: "entrance_left"},
    { from: "1",             to: "100"          },
    { from: "1",             to: "152"          },
    { from: "1",             to: "2"            },
    { from: "1",             to: "8"            },
    { from: "1",             to: "0"            },
    { from: "2",             to: "1"            },
    { from: "2",             to: "3"            },
    { from: "2",             to: "40"           },
    { from: "3",             to: "2"            },
    { from: "3",             to: "4"            },
    { from: "3",             to: "42"           },
    { from: "4",             to: "34"           },
    { from: "4",             to: "3"            },
    { from: "4",             to: "5"            },
    { from: "4",             to: "11"           },
    { from: "5",             to: "4"            },
    { from: "5",             to: "6"            },
    { from: "5",             to: "18"           },
    { from: "6",             to: "5"            },
    { from: "6",             to: "12"           },
    { from: "6",             to: "16"           },
    { from: "7",             to: "16"           },
    { from: "7",             to: "447"          },
    { from: "7",             to: "12"           },
    { from: "7",             to: "105"          },
    { from: "8",             to: "40"           },
    { from: "8",             to: "1"            },
    { from: "8",             to: "0"            },
    { from: "8",             to: "cleaning"     },
    { from: "9",             to: "101"          },
    { from: "9",             to: "22"           },
    { from: "9",             to: "447"          },
    { from: "9",             to: "checkout_1"   },
    { from: "11",            to: "42"           },
    { from: "11",            to: "18"           },
    { from: "11",            to: "4"            },
    { from: "12",            to: "6"            },
    { from: "12",            to: "22"           },
    { from: "12",            to: "7"            },
    { from: "16",            to: "18"           },
    { from: "16",            to: "7"            },
    { from: "16",            to: "6"            },
    { from: "18",            to: "11"           },
    { from: "18",            to: "16"           },
    { from: "18",            to: "5"            },
    { from: "22",            to: "101"          },
    { from: "22",            to: "12"           },
    { from: "22",            to: "9"            },
    { from: "447",           to: "7"            },
    { from: "447",           to: "9"            },
    { from: "447",           to: "352"          },
    { from: "447",           to: "checkout_1"   },
    { from: "cleaning",      to: "vitamins"     },
    { from: "cleaning",      to: "8"            },
    { from: "cleaning",      to: "0"            },
    { from: "cleaning",      to: "entrance_left"},
    { from: "vitamins",      to: "cleaning"     },
    { from: "vitamins",      to: "pharmacy"     },
    { from: "pharmacy",      to: "vitamins"     },
    { from: "pharmacy",      to: "152"          },
    { from: "34",            to: "100"          },
    { from: "34",            to: "101"          },
    { from: "34",            to: "4"            },
    { from: "40",            to: "8"            },
    { from: "40",            to: "42"           },
    { from: "40",            to: "2"            },
    { from: "42",            to: "40"           },
    { from: "42",            to: "11"           },
    { from: "42",            to: "3"            },
    { from: "100",           to: "34"           },
    { from: "100",           to: "1"            },
    { from: "100",           to: "152"          },
    { from: "101",           to: "34"           },
    { from: "101",           to: "9"            },
    { from: "101",           to: "22"           },
    { from: "101",           to: "checkout_1"   },
    { from: "152",           to: "100"          },
    { from: "152",           to: "1"            },
    { from: "152",           to: "0"            },
    { from: "152",           to: "pharmacy"     },
    { from: "152",           to: "entrance_left"},
    { from: "105",           to: "351"          },
    { from: "105",           to: "7"            },
    { from: "105",           to: "0"            },
    { from: "105",           to: "entrance_right"},
    { from: "351",           to: "105"          },
    { from: "351",           to: "352"          },
    { from: "352",           to: "351"          },
    { from: "352",           to: "447"          },
    { from: "352",           to: "entrance_right"},
    { from: "entrance_left", to: "0"            },
    { from: "entrance_left", to: "cleaning"     },
    { from: "entrance_left", to: "152"          },
    { from: "entrance_right",to: "352"          },
    { from: "entrance_right",to: "105"          },
    { from: "checkout_1",    to: "9"            },
    { from: "checkout_1",    to: "447"          },
    { from: "checkout_1",    to: "101"          },
    { from: "checkout_1",    to: "checkout_2"   },
    { from: "checkout_2",    to: "checkout_1"   },
    { from: "checkout_2",    to: "checkout_3"   },
    { from: "checkout_3",    to: "checkout_2"   },
    { from: "checkout_3",    to: "exit"         },
    { from: "exit",          to: "checkout_3"   },
  ],
};
